import type { LucideIcon } from "lucide-react";
import {
  Plane,
  ArrowDownRight,
  ArrowLeftRight,
  ArrowUpRight,
  Baby,
  BadgeDollarSign,
  Banknote,
  BarChart3,
  Bike,
  BookOpen,
  BriefcaseBusiness,
  Bus,
  CakeSlice,
  Camera,
  Car,
  Cat,
  Circle,
  Clapperboard,
  Coffee,
  CreditCard,
  Dumbbell,
  Gamepad2,
  Fuel,
  Gift,
  GraduationCap,
  HandHeart,
  Handshake,
  Heart,
  HeartPulse,
  Home,
  Hotel,
  HousePlug,
  Landmark,
  Laptop,
  List,
  MoreHorizontal,
  Music,
  PawPrint,
  Phone,
  PiggyBank,
  Pizza,
  ReceiptText,
  Repeat2,
  Settings,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  Smartphone,
  Sparkles,
  Store,
  Target,
  TrainFront,
  TreePine,
  Trophy,
  Umbrella,
  Utensils,
  WalletCards,
  WandSparkles,
  WashingMachine,
  Wifi,
  Wrench,
  Users,
} from "lucide-react";

const map: Record<string, LucideIcon> = {
  home: Home,
  list: List,
  target: Target,
  chart: BarChart3,
  wallet: WalletCards,
  settings: Settings,
  circle: Circle,
  basket: ShoppingBasket,
  coffee: Coffee,
  car: Car,
  briefcase: BriefcaseBusiness,
  gift: Gift,
  sparkles: Sparkles,
  heart: Heart,
  health: HeartPulse,
  "hand-heart": HandHeart,
  book: BookOpen,
  bag: ShoppingBag,
  handshake: Handshake,
  family: Users,
  card: CreditCard,
  cash: Banknote,
  repeat: Repeat2,
  more: MoreHorizontal,
  transport: Bus,
  restaurant: Utensils,
  coins: BadgeDollarSign,
  "trend-up": ArrowUpRight,
  "trend-down": ArrowDownRight,
  arrows: ArrowLeftRight,
  assistant: WandSparkles,
  savings: PiggyBank,
  bank: Landmark,
  plane: Plane,
  train: TrainFront,
  bike: Bike,
  fuel: Fuel,
  phone: Phone,
  smartphone: Smartphone,
  laptop: Laptop,
  wifi: Wifi,
  receipt: ReceiptText,
  store: Store,
  pizza: Pizza,
  cake: CakeSlice,
  hotel: Hotel,
  camera: Camera,
  music: Music,
  movie: Clapperboard,
  game: Gamepad2,
  gym: Dumbbell,
  trophy: Trophy,
  education: GraduationCap,
  clothes: Shirt,
  pet: PawPrint,
  cat: Cat,
  baby: Baby,
  repair: Wrench,
  appliances: WashingMachine,
  utilities: HousePlug,
  vacation: Umbrella,
  nature: TreePine,
};

export function CategoryGlyph({
  name,
  size = 20,
}: {
  name?: string;
  size?: number;
}) {
  const Icon = map[name || "circle"] || Circle;
  return <Icon size={size} strokeWidth={2} />;
}
